apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2                  # 2 копии приложения
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ghcr.io/bakaleyshik/my-app:latest
        ports:
          - containerPort: 8000
        env:
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: APP_ENV
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: my-app-secret
                key: API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5