apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2                  # 2 копии приложения
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/bakaleyshik/my-app:latest
          ports:
            - containerPort: 8000
          livenessProbe:       # "жив ли контейнер?"
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:      # "готов ли принимать трафик?"
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5